'''def numbers():
    print("hello my name is mukesh kumar ")
numbers()
    '''
'''def welcome(name):
    print("hello bhai",name)
welcome("chandan")
welcome("mukesh")  
print("thanku jii") '''

'''def introduced(name,age):
    print("name",name)
    print("age",age)
introduced("mukesh","24")
introduced("panku","22")
print("thnku  ")'''

'''def add(a,b):
    return a + b
x = add(10,20)
y = add(40,20)
print(x)
print(x+300)
print(400+x)
print(y)  ''''''''


'''''''
def add(a,b):
    return a + b 
def subtract(a,b):
    return a - b
def multiply(a,b):
    return a * b
def divide(a,b):
    return a / b
print(add(10,20))

print(subtract(20,5))

print(multiply(6,7))

print(divide(20,4))'''
''''
def squre(x):
    return x * x 
def cube (x):
    return x * x * x
print(squre(2))
print(cube(2))'''

